version: '3.7'
services:
  service:
    image: vlsp:latest
    build:
      context: .  
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:5000"