name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u hungln45 -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t hungln45/vlsp2023:latest .
      working-directory: .

    - name: Push Docker image
      run: docker push hungln45/vlsp2023:latest

    - name: Logout from Docker Hub
      run: docker logout
